### ISSUE TITLE
How to use th:href in a mail template?

### ISSUE THREAD

**Issue by diegoacuna** [thymeleaf/thymeleafexamples-springmail#2]
Hi, I'm using the basecode in this repo to use thymeleaf as a template system for sending emails. So far, so good, but I'm facing one problem, when I use th:href in the template I get the next exception (using tomcat6):

```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Link base "/users/invitation" cannot be context relative (/) or page relative unless you implement the org.thymeleaf.context.IWebContext interface (context is of class: org.thymeleaf.context.Context) (invitation:21)
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:927)
org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:822)
javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:796)
javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)...
```

Can I use th:href in a email template and if not what can I do to print app's urls in my email template?

Thanks.

**Comment by jmiguelsamper** [comment]
Hello,

in order to use the th:href processor you need a WebContext instead of a plain Context. See Context creation in
    https://github.com/thymeleaf/thymeleafexamples-springmail/blob/2.1-master/src/main/java/thymeleafexamples/springmail/service/EmailService.java

You can replace this Context creation by one similar (or the same) to this class
   https://github.com/thymeleaf/thymeleaf-itutorial/blob/2.1-master/src/main/java/org/thymeleaf/itutorial/OfflineSpringWebContext.java

Regards,
   Zemi

**Comment by diegoacuna** [comment]
Thanks. Solved.

**Comment by stephane-dereppe** [comment]
Hi,

any idea how to achieve this with Spring 5 (Spring boot 2)?

`SpringWebContext ` is available in `org.thymeleaf.spring4.context` ? But is not there since tag `thymeleaf-spring4-3.0.0.RELEASE`
