### ISSUE TITLE
JavaConfig version does not work with tomcat7-maven-plugin

### ISSUE THREAD

**Issue by jmiguelsamper** [thymeleaf/thymeleafexamples-springmail#5]
The new version of the Spring mail example (currently at 2.1-dev) requires Servlet 3.0 in order to avoid web.xml configuration (it's nice to have Java config instead of web.xml the same way it is for Spring configuration).

The application has tomcat7-maven-plugin configured to allow command line execution using

```
     mvn tomcat7:run
```

However, due to a bug on the tomcat7-maven-plugin (https://issues.apache.org/jira/browse/MTOMCAT-246) the loading of classpath resources does not work.

The application uses a ClassLoaderTemplateResolver to load email templates to highlight that a web environment is not required to compose emails with Thymeleaf.

**Comment by danielfernandez** [comment]
But... this was working before, right? what did the switch to JavaConfig change that made this appear?

From what I see, it seems the "tomcat8" plugin has the same issues so... if all tomcat-based possibilities are buggy, what about providing a jetty-based configuration for this app? There is a jetty maven plugin...

**Comment by jmiguelsamper** [comment]
Yes, it works OK with Tomcat 6 and Servlet 2.4 web.xml (what we have on 2.1-master).

Maven Tomcat 6 plugin works OK, the problem arose at switching to Tomcat 7. I did that because I thought that having a Servlet 3.0 Java config for the web application (instead of a web.xml configuration) was consistent with the change for Spring Java config.

**Comment by danielfernandez** [comment]
It seems to be working now, so I'm closing this.
