### ISSUE TITLE
How to solve this problem Field htmlTemplateEngine required a single bean ?

### ISSUE THREAD

**Issue by MarwenBenTalebAli** [thymeleaf/thymeleafexamples-springmail#8]
Hello,

I am tring to add a Contact Form with Spring Boot and Thymeleaf to my application. I followed your example. I am using Spring Tool Suite (Version: 3.9.2.RELEASE Build Id: 201712211026 Platform: Eclipse Neon.3 (4.6.3)).

I followed the documentation but It did not help me so much.

I imported your project but I could not launch it.  This is what I did 

1- Run as -> Maven Clean  : BUILD SUCCESS
2- Then I did Run as Maven install : BUILD FAILURE

> Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war) on project springmail: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode)

I can not launch the project as spring application. I could not test your project.

Then when working into my project, I added these classes (SpringBusinessConfig, SpringMailConfig, SendingController, EmailService) and I changed my "WebMvcConfig" to be like your "SpringWebConfig" and I added the mail folder in resources.

but I could not launch the application.

APPLICATION FAILED TO START

Description:

> Field htmlTemplateEngine in com.example.springmail.service.EmailService required a single bean, but 2 were found: - emailTemplateEngine: defined by method 'emailTemplateEngine' in class path resource [com/example/springmail/configuration/SpringMailConfig.class] - templateEngine: defined by method 'templateEngine' in class path resource [com/example/springmail/web/SpringWebConfig.class]
> 
> Action:
> 
> Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

1- How to launch your project?
2- What should I add to my project so that it works?
3- Can you add a little detail in your documentation? In the document, it does not mention the dependencies to add. (making a small example from the beginning with more details will be enough).

Can u pls help me and thank you?

**Comment by danielfernandez** [comment]
This application is lacking the configuration needed for the `maven-war-plugin` to not require a `web.xml` file at build time.

**Comment by danielfernandez** [comment]
@MarwenBenTalebAli BTW, about how to launch this project, the `README` suggested using `mvn tomcat7:run`, which does not use the `maven-war-plugin` at all and directly launches the application into a Tomcat7 from Maven.
